import Head from "next/head";
import Slider from "../components/Slider";
import Card from "../components/Card";
import CardSection from "../components/CardSection";
// import Dropdown from "../components/Userdropdown";

export default function Home({ content }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-16 pb-10">
        <Slider />
      </div>

      {content.map((item) => (
        <CardSection key={item._id} id={item._id} name={item.categoryName} />
      ))}
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetch("http://localhost:3000/api/db/category");
  const content = await data.json();

  return {
    props: { content },
  };
}
