import Head from "next/head";
import Slider from "../components/Slider";
import Card from "../components/Card";
// import Example from "../components/Userdropdown";
import Dropdown from "../components/Userdropdown";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-16 pb-10">
        <Slider />
      </div>

      <div className="pt-16">
        <h2 className="text-center text-4xl font-semibold">Man fashion</h2>
        <div className="py-6 flex flex-wrap justify-center align-middle items-center">
          <Card />
          <Card />
          <Card />
        </div>
      </div>
      <div className="pt-16">
        <h2 className="text-center text-4xl font-semibold">Man fashion</h2>
        <div className="py-6 flex flex-wrap justify-center align-middle items-center">
          <Card />
          <Card />
          <Card />
        </div>
      </div>
    </div>
  );
}
